
// THIS FILE IS AUTO-GENERATED BY scripts/generate-content.cjs
// DO NOT EDIT THIS FILE DIRECTLY. EDIT THE MARKDOWN FILES IN /data INSTEAD.

import { BlogPost, Project, Experience, Skill } from '../types';

export const LAST_UPDATED = "2025年12月16日 下午11:42:12";

export const PERSONAL_INFO = {
  "name": "Alex Chen",
  "title": "嵌入式系统工程师",
  "about": "这里是我的个人简介正文。我喜欢在这个部分写一些 Markdown 内容。",
  "location": "Shanghai, China",
  "email": "alex@example.com",
  "github": "https://github.com/yourname",
  "linkedin": "https://linkedin.com/in/yourname"
};

export const SKILLS: Skill[] = [
  {
    "category": "编程语言",
    "items": [
      "C",
      "C++",
      "Python",
      "Rust"
    ]
  },
  {
    "category": "硬件开发",
    "items": [
      "STM32",
      "PCB Design",
      "FPGA"
    ]
  }
];

export const PROJECTS: Project[] = [];

export const EXPERIENCES: Experience[] = [];

export const BLOG_POSTS: BlogPost[] = [
  {
    "id": "my-post",
    "title": "我的第一篇自动化博客",
    "excerpt": "这是通过脚本自动生成的文章摘要。",
    "date": "2025-12-16",
    "tags": [
      "DevOps",
      "Obsidian"
    ],
    "readTime": "5 min read",
    "coverImage": "",
    "content": "\r\n# Hello World\r\n\r\n这是正文内容。"
  }
];


export const generateResumeContext = (info: any, skills: any[], exps: any[], projects: any[]) => `
Name: ${info.name}
Role: ${info.title}
About: ${info.about}
`;


export const RESUME_CONTEXT = generateResumeContext(PERSONAL_INFO, SKILLS, EXPERIENCES, PROJECTS);
