const fs = require('fs');
const path = require('path');
const matter = require('gray-matter');
const glob = require('glob');

// 1. 修正：输出路径改回根目录下的 data
const DATA_DIR = path.join(__dirname, '../data');
const OUTPUT_FILE = path.join(__dirname, '../data/content.ts');

// 确保目录存在
['profile', 'projects', 'experiences', 'blog'].forEach(dir => {
    const fullPath = path.join(DATA_DIR, dir);
    if (!fs.existsSync(fullPath)) {
        fs.mkdirSync(fullPath, { recursive: true });
    }
});

// 辅助函数：将 Windows 反斜杠路径转换为 glob 能识别的正斜杠
const formatPathForGlob = (filePath) => {
    return filePath.replace(/\\/g, '/');
};

const parseSkills = (data) => data.skills || [];

const parseExperienceDescription = (content) => {
    return content
        .split('\n')
        .map(line => line.trim())
        .filter(line => line.startsWith('- ') || line.startsWith('* '))
        .map(line => line.substring(2).trim());
};

// 处理个人资料
const processProfile = () => {
    // 2. 修正：在这里加上 formatPathForGlob
    const pattern = formatPathForGlob(path.join(DATA_DIR, 'profile/*.md'));
    const files = glob.sync(pattern);

    if (files.length === 0) {
        console.warn("警告: 在 data/profile 下没找到 .md 文件");
        return { info: {}, skills: [] };
    }

    const fileContent = fs.readFileSync(files[0], 'utf8');
    const { data, content } = matter(fileContent);

    return {
        info: {
            name: data.name || "Your Name",
            title: data.title || "Developer",
            about: content.trim(),
            location: data.location || "",
            email: data.email || "",
            github: data.github || "",
            linkedin: data.linkedin || ""
        },
        skills: parseSkills(data)
    };
};

// 处理项目
const processProjects = () => {
    const pattern = formatPathForGlob(path.join(DATA_DIR, 'projects/*.md'));
    const files = glob.sync(pattern);
    return files.map(file => {
        const { data, content } = matter(fs.readFileSync(file, 'utf8'));
        return {
            id: path.basename(file, '.md'),
            title: data.title || "Untitled",
            description: content.trim(),
            techStack: data.techStack || [],
            imageUrl: data.imageUrl || "",
            category: data.category || "Software",
            githubUrl: data.githubUrl,
            demoUrl: data.demoUrl
        };
    });
};

// 处理经历
const processExperiences = () => {
    const pattern = formatPathForGlob(path.join(DATA_DIR, 'experiences/*.md'));
    const files = glob.sync(pattern);
    const exps = files.map(file => {
        const { data, content } = matter(fs.readFileSync(file, 'utf8'));
        return {
            id: path.basename(file, '.md'),
            role: data.role || "Role",
            company: data.company || "Company",
            period: data.period || "Present",
            order: data.order || 0,
            description: parseExperienceDescription(content)
        };
    });
    return exps.sort((a, b) => (b.order || 0) - (a.order || 0));
};

// 处理博客
const processBlogs = () => {
    const pattern = formatPathForGlob(path.join(DATA_DIR, 'blog/*.md'));
    const files = glob.sync(pattern);
    const posts = files.map(file => {
        const { data, content } = matter(fs.readFileSync(file, 'utf8'));
        return {
            id: path.basename(file, '.md'),
            title: data.title || "No Title",
            excerpt: data.excerpt || "",
            date: data.date ? new Date(data.date).toISOString().split('T')[0] : new Date().toISOString().split('T')[0],
            tags: data.tags || [],
            readTime: data.readTime || "5 min read",
            coverImage: data.coverImage,
            content: content
        };
    });
    return posts.sort((a, b) => new Date(b.date) - new Date(a.date));
};

// 生成内容
const profile = processProfile();
const projects = processProjects();
const experiences = processExperiences();
const blogPosts = processBlogs();

// 简单的 resume context 字符串生成（为了减少依赖）
const generateResumeContextString = `
export const generateResumeContext = (info: any, skills: any[], exps: any[], projects: any[]) => \`
Name: \${info.name}
Role: \${info.title}
About: \${info.about}
\`;
`;

const fileContent = `
// THIS FILE IS AUTO-GENERATED BY scripts/generate-content.cjs
// DO NOT EDIT THIS FILE DIRECTLY. EDIT THE MARKDOWN FILES IN /data INSTEAD.

import { BlogPost, Project, Experience, Skill } from '../types';

export const LAST_UPDATED = "${new Date().toLocaleString()}";

export const PERSONAL_INFO = ${JSON.stringify(profile.info, null, 2)};

export const SKILLS: Skill[] = ${JSON.stringify(profile.skills, null, 2)};

export const PROJECTS: Project[] = ${JSON.stringify(projects, null, 2)};

export const EXPERIENCES: Experience[] = ${JSON.stringify(experiences, null, 2)};

export const BLOG_POSTS: BlogPost[] = ${JSON.stringify(blogPosts, null, 2)};

${generateResumeContextString}

export const RESUME_CONTEXT = generateResumeContext(PERSONAL_INFO, SKILLS, EXPERIENCES, PROJECTS);
`;

fs.writeFileSync(OUTPUT_FILE, fileContent);
console.log(`Successfully generated content to ${OUTPUT_FILE}`);